# Generated by Django 2.2.5 on 2019-10-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asientos', '0001_initial'),
        ('pagos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEvento', models.CharField(max_length=45)),
                ('pago', models.DecimalField(decimal_places=4, max_digits=15)),
                ('reserva', models.BooleanField()),
                ('idAsiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos.Asiento')),
                ('idTipoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Pago')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
        ),
    ]
