<<<<<<< HEAD
# Generated by Django 2.2.4 on 2019-09-24 21:19
=======
# Generated by Django 2.2.5 on 2019-10-05 21:18
>>>>>>> felipe

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
    ]
