# Generated by Django 2.2.5 on 2019-10-01 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipolocalidad', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=4, max_digits=15)),
                ('cantidadAsientos', models.IntegerField()),
                ('cantidadAsientosDisponible', models.IntegerField(blank=True)),
                ('cantidadAsientosOcupados', models.IntegerField(blank=True)),
                ('codigoEventos', models.CharField(max_length=45, null=True)),
                ('idTipoLocalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tipolocalidad.TipoLocalidad')),
            ],
        ),
    ]
