# Generated by Django 2.2.5 on 2019-09-21 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipolocalidad', '0001_initial'),
        ('eventos', '0001_initial'),
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['-tipo']},
        ),
        migrations.AddField(
            model_name='localidad',
            name='idEventos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='idTipoLocalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tipolocalidad.TipoLocalidad'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='canitidadAsientosDisponible',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='cantidadAsientosOcupados',
            field=models.IntegerField(blank=True),
        ),
    ]
