# Generated by Django 2.2.5 on 2019-09-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0002_auto_20190921_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['-costo']},
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='tipo',
        ),
    ]
