# Generated by Django 2.2.5 on 2019-09-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0003_auto_20190921_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={},
        ),
    ]
