# Generated by Django 2.2.5 on 2019-09-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0004_auto_20190921_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='costo',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
