# Generated by Django 2.2.5 on 2019-10-12 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEventos', models.CharField(max_length=45, null=True)),
                ('idPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.Pago')),
            ],
        ),
    ]
